### ISSUE TITLE
Linux: arduino-cli.app disappeared in version 0.7.0

### ISSUE THREAD

**Issue by SpintroniK** [vscode-arduino/vscode-arduino#26] opened 2024-09-04 19:31 UTC
Upgrading to version 0.7.0 on debian today caused an error message on startup:
```text
The bundled Arduino CLI could not be marked executable. Ensure that VS Code is able to execute: /home/jeremy/.vscode/extensions/vscode-arduino.vscode-arduino-community-0.7.0-linux-x64/assets/platform/linux-x64/arduino-cli/arduino-cli.app
```

The `arduino-cli.app` file doesn't exist any more, as shown here:
```bash
ls -lh /home/jeremy/.vscode/extensions/vscode-arduino.vscode-arduino-community-0.7.0-linux-x64/assets/platform/
total 4.0K
drwxrwxr-x 3 jeremy jeremy 4.0K Sep  2 20:37 darwin-arm64
```

**Comment by arvitus** [comment] 2024-09-05 14:04
same for windows. It seems like it doesn't get installed automatically. When downloading the cli manually and placing it in the intended folder, everything works though.

**Comment by vicatcu** [comment] 2024-09-05 15:54
Confirmed downloading the latest release from https://arduino.github.io/arduino-cli/0.35/installation/, extracting the executable, creating the requisite folder structure in the extensions, moving / renaming the executable to what the extension is expecting (arduino-cli.app), then `chmod +x`ing the executable seems to work.

**Comment by lersi** [comment] 2024-09-08 21:51
Please let me know if this issue persists in release 0.7.1

**Comment by spusuf** [comment] 2024-09-09 00:00
> Please let me know if this issue persists in release 0.7.1

The issue does persist yes, there is a darwin-arm64 but no linux-x64 folder as expected in the error message. Making the directory and downloading arduino cli and setting as executable manually does not work. Same error is provided

**Comment by serek4** [comment] 2024-09-10 17:26
this works for me
> Confirmed downloading the latest release from https://arduino.github.io/arduino-cli/0.35/installation/, extracting the executable, creating the requisite folder structure in the extensions, moving / renaming the executable to what the extension is expecting (arduino-cli.app), then `chmod +x`ing the executable seems to work.

btw latest version is [1.0.4](https://arduino.github.io/arduino-cli/1.0/)

**Comment by lersi** [comment] 2024-09-10 19:41
Does this also happens if you install the extension from VSIX file (available on the release page)?
The issue seems to happen only when installing from market place

**Comment by vicatcu** [comment] 2024-09-10 19:55
@lersi Sorry I can't help confirm that, I've only ever installed extensions through the marketplace-- I don't know how from the command line.

**Comment by lersi** [comment] 2024-09-10 19:57
From farther digging the extension files in the market place are messed up, and the serve the wrong VSIX file for the architecture.
I need to make sure if I did something wrong or is there a problem with their publish tool

**Comment by lersi** [comment] 2024-09-10 20:11
Their tool is so messed up, I will now run through versions until I find the correct way of publishing

**Comment by lersi** [comment] 2024-09-10 20:34
Please let me know if this issue persists in version "0.7.2" (dummy version)

**Comment by lersi** [comment] 2024-09-11 08:35
So the problem was indeed with vsce tool, closing this issue as solve

**Closed by lersi** 2024-09-11 08:35 UTC
